name: flutter_posts
description: "This Flutter project is built following the Clean Architecture principles to ensure scalability, maintainability, and clear separation of concerns."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
